---
name: Build and Publish

on:
  schedule:
  - cron: "0 0 * * *"
  pull_request:
  push:
    branches:
    - "!gh-pages"
    - "**"
    tags:
    - "v*"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - name: Grab source
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set pipx default Python version
      if: matrix.os != 'windows-latest'
      run: echo "PIPX_DEFAULT_PYTHON=$(which python)" >> $GITHUB_ENV

    - name: Set pipx default Python version on Windows
      if: matrix.os == 'windows-latest'
      run: |
        # Find the correct Python 3.12 executable path
        $pythonPath = (Get-Command python).Source
        echo "PIPX_DEFAULT_PYTHON=$pythonPath" >> $Env:GITHUB_ENV
      shell: powershell

    - name: Setup Environment
      run: |
        make env

    - name: Check format
      run: |
        make format

    - name: Build
      run: |
        make build install-dev

    - name: Run -- show help
      run: |
        senfd --help

    - name: Run -- actual IO
      run: |
        senfd example/example.docx --output output

    - uses: actions/upload-artifact@v4
      with:
        name: documents-enriched-${{ matrix.os }}-${{ matrix.python-version }}
        path: output

    - name: Run -- tests
      run: |
        make test

    - uses: actions/upload-artifact@v4
      with:
        name: coverage-html-${{ matrix.os }}-${{ matrix.python-version }}
        path: htmlcov

    - name: Upload coverage to Coveralls
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
      uses: coverallsapp/github-action@v2.3.0
      with:
        file: coverage.lcov
        format: lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        make release